routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::resource('camion', 'CamionController');
Route::resource('categoria', 'CategoriaController');
Route::resource('detalleentrada', 'DetalleEntradaController');
Route::resource('detallesalida', 'DetalleSalidaController');
Route::resource('devolucion', 'DevolucionController');
Route::resource('entrada', 'EntradaController');
Route::resource('inventario', 'InventarioController');
Route::resource('permiso', 'PermisoController');
Route::resource('producto', 'ProductoController');
Route::resource('proveedor', 'ProveedorController');
Route::resource('rol', 'RolController');
Route::resource('rolpermiso', 'RolPermisoController');
Route::resource('salida', 'SalidaController');
Route::resource('unidadmedida', 'UnidadMedidaController');
Route::resource('users', 'UsersController');

app/Proveedor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Proveedor extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['nombre', 'correo', 'telefono', 'created_at', 'updated_at', 'deleted_at'];
    protected $table = 'proveedor';
    protected $primaryKey = 'proveedor_id';
    
    //Relacion Uno a Mucho
    public function producto(){
        return $this->hasMany('App\Producto', 'proveedor_id', 'proveedor_id');
    }

    //Relacion Uno a Mucho
    public function entrada(){
        return $this->hasMany('App\Entrada', 'proveedor_id', 'proveedor_id');
    }
}

app/Http/Controllers/ProveedorController.php
<?php

namespace App\Http\Controllers;

use App\Proveedor;
use Illuminate\Http\Request;

class ProveedorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proveedores = Proveedor::get();
        return view('proveedor.index', [
            'proveedores' => $proveedores
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $proveedor = new Proveedor;
        return view('proveedor.create', [
            'proveedor' => $proveedor
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'nombre'   => 'Required | String',
            'correo'   => '',
            'telefono' => ''
        ]);

        Proveedor::create([
            'nombre'        => request('nombre'),
            'correo'   => request('correo'),
            'telefono'   => request('telefono'),
        ]);

        return redirect()->route('proveedor.index')
            ->with('success', "¡Proveedor agregado!" );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('proveedor.edit', [
            'proveedor' => Proveedor::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'nombre'   => 'Required | String',
            'correo'   => '',
            'telefono' => ''
        ]);

        $proveedor = Proveedor::find($id);
        $proveedor->nombre   = request('nombre');
        $proveedor->correo   = request('correo');
        $proveedor->telefono = request('telefono');
        $proveedor->save();

        return redirect()->route('proveedor.index')
            ->with('success', "¡Proveedor editado!" );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $proveedor = Proveedor::find($id);
            $proveedor->delete();
            return redirect()->route('proveedor.index')
                ->with('success', "Proveedor eliminado correctamente.");
        } catch (Throwable $e) {
            return redirect()->route('proveedor.index')
            ->with('danger', "No fue posible completar esta operación :(.");
        }
    }
}

resources/views/proveedor/create.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Nuevo Proveedor
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <!--begin::Form-->
                        <form method="POST" action="{{ route('proveedor.store') }}" autocomplete="off">
                            @csrf

                            @include('proveedor.form')

                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection

resources/views/proveedor/edit.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Editar Proveedor
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <!--begin::Form-->
                        <form method="POST" action="{{ route('proveedor.update', $proveedor) }}" autocomplete="off">
                            @csrf
                            @method('PATCH')

                            @include('proveedor.form')

                        </form>
                        <!--end::Form-->
                        <div class="card-footer">
                            <form method="POST" action="{{ route('proveedor.destroy', $proveedor) }}">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-block">¡Eliminar Permanentemente!</button>
                            </form>
                        </div>
                    </div>
                    <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection

resources/views/proveedor/form.blade.php
<div class="card-body">
    @if ( $errors->any() )
        <div class="form-group mb-8">
            <div class="alert alert-custom alert-danger" role="alert">
                <div class="alert-icon"><span
                        class="svg-icon svg-icon-default svg-icon-xl">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Tools/Compass.svg--><svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="24px" height="24px" viewBox="0 0 24 24"
                            version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24"/>
                                <circle fill="#000000" opacity="0.3" cx="12" cy="12" r="10"/>
                                <path d="M12.0355339,10.6213203 L14.863961,7.79289322 C15.2544853,7.40236893 15.8876503,7.40236893 16.2781746,7.79289322 C16.6686989,8.18341751 16.6686989,8.81658249 16.2781746,9.20710678 L13.4497475,12.0355339 L16.2781746,14.863961 C16.6686989,15.2544853 16.6686989,15.8876503 16.2781746,16.2781746 C15.8876503,16.6686989 15.2544853,16.6686989 14.863961,16.2781746 L12.0355339,13.4497475 L9.20710678,16.2781746 C8.81658249,16.6686989 8.18341751,16.6686989 7.79289322,16.2781746 C7.40236893,15.8876503 7.40236893,15.2544853 7.79289322,14.863961 L10.6213203,12.0355339 L7.79289322,9.20710678 C7.40236893,8.81658249 7.40236893,8.18341751 7.79289322,7.79289322 C8.18341751,7.40236893 8.81658249,7.40236893 9.20710678,7.79289322 L12.0355339,10.6213203 Z" fill="#000000"/>
                            </g>
                        </svg>
                        <!--end::Svg Icon--></span></div>
                <div class="alert-text">
                    @foreach ($errors->all() as $error)
                        {{ $error }} <br>
                    @endforeach
                </div>
            </div>
        </div>                    
    @endif
    
    <div class="form-group">
        <label name="nombre">Nombre Proveedor<span class="text-danger">*</span></label>
        <input name="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" value="{{ old('nombre', $proveedor->nombre) }}" placeholder="Proveedor" />
    </div>

    <div class="form-group mb-1">
         <label name="correo" for="exampleTextarea">Correo electrónico</label>
        <input class="form-control @error('correo') is-invalid @enderror" type="email" name="correo" value="{{ old('correo', $proveedor->correo) }}">
    </div>

    <div class="form-group mb-1">
        <label name="telefono" for="exampleTextarea">Teléfono</label>
        <input type="tel" class="form-control @error('telefono') is-invalid @enderror" name="telefono" pattern="[0-9]{10}" value="{{ old('telefono', $proveedor->telefono) }}">
    </div>

         
	    
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary btn-block">Guardar</button>
    <a href="{{ route('proveedor.index') }}" class="btn btn-secondary btn-block">Cancelar</a>
</div>

resources/views/proveedor/index.blade.php
@extends('layouts.index')

@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Camiones 
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <a href="{{ route('proveedor.create') }}" class="btn btn-light-primary font-weight-bolder btn-sm">
                    Añadir Nuevo Proveedor
                </a>
                <!--end::Actions-->
            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
            @include('layouts.sessiones')
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <!--begin::Form-->
                <div class="card-body">
                    <!--begin: Datatable-->
                    <table class="table table-striped table-bordered" id="kt_datatable">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($proveedores ?? '' as $proveedor)
                                <tr>
                                    <td>{{ $proveedor->nombre }}</td>
                                    <td>{{ $proveedor->correo }}</td>
                                    <td>{{ $proveedor->telefono }}</td>
                                    <td>
                                        <a href="{{ route('proveedor.edit', $proveedor) }}" title="Editar" class="mr-5"><i class="flaticon2-pen text-primary"></i></a>
                                        <a href="{{ route('proveedor.edit', $proveedor) }}" title="Eliminar" class="mr-5"><i class="flaticon-delete text-primary"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!--end: Datatable-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection