routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::resource('camion', 'CamionController');
Route::resource('categoria', 'CategoriaController');
Route::resource('detalleentrada', 'DetalleEntradaController');
Route::resource('detallesalida', 'DetalleSalidaController');
Route::resource('devolucion', 'DevolucionController');
Route::resource('entrada', 'EntradaController');
Route::resource('inventario', 'InventarioController');
Route::resource('permiso', 'PermisoController');
Route::resource('producto', 'ProductoController');
Route::resource('proveedor', 'ProveedorController');
Route::resource('rol', 'RolController');
Route::resource('rolpermiso', 'RolPermisoController');
Route::resource('salida', 'SalidaController');
Route::resource('unidadmedida', 'UnidadMedidaController');
Route::resource('users', 'UsersController');

app/Camion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Camion extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $fillable = ['nombre', 'descripcion', 'created_at', 'updated_at', 'deleted_at'];
    protected $table = 'camion';
    protected $primaryKey = 'camion_id';

    //Relacion Uno a Mucho
    public function salida(){
        return $this->hasMany('App\Salida', 'camion_id', 'camion_id');
    }
}

app/Http/Controllers/CamionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Camion;

class CamionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $camiones = Camion::get();
        return view('camion.index', [
            'camiones' => $camiones
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $camion = new Camion;
        return view('camion.create', [
            'camion' => $camion
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        request()->validate([
            'nombre' => 'Required | String',
            'descripcion' => ''
        ]);

        Camion::create([
            'nombre'        => request('nombre'),
            'descripcion'   => request('descripcion'),
        ]);

        return redirect()->route('camion.index')
            ->with('success', "¡Camión agregado!" );
    }

    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($camion)
    {
        //
        return view('camion.edit', [
            'camion' => Camion::find($camion)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $camion)
    {
        //
        request()->validate([
            'nombre' => 'Required | String',
            'descripcion' => ''
        ]);

        $camion = Camion::find($camion);
        $camion->nombre = request('nombre');
        $camion->descripcion = request('descripcion');
        $camion->save();

        return redirect()->route('camion.index')
            ->with('success', "¡Camión editado!" );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($camion)
    {
        //
        try {
            $camion = Camion::find($camion);
            $camion->delete();
            return redirect()->route('camion.index')
                ->with('success', "Camión eliminado correctamente.");
        } catch (Throwable $e) {
            return redirect()->route('camion.index')
            ->with('danger', "No fue posible completar esta operación :(.");
        }
    }
}

resources/views/camion/create.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Nuevo Camión
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <!--begin::Form-->
                        <form method="POST" action="{{ route('camion.store') }}" autocomplete="off">
                            @csrf

                            @include('camion.form')

                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection

resources/views/camion/edit.blade.php
@extends('layouts.index')
@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Editar Camion
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <!--begin::Form-->
                        <form method="POST" action="{{ route('camion.update', $camion) }}" autocomplete="off">
                            @csrf
                            @method('PATCH')

                            @include('camion.form')

                        </form>
                        <!--end::Form-->
                        <div class="card-footer">
                            <form method="POST" action="{{ route('camion.destroy', $camion) }}">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-block">¡Eliminar Permanentemente!</button>
                            </form>
                        </div>
                    </div>
                    <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection

resources/views/camion/form.blade.php
<div class="card-body">
    @if ( $errors->any() )
        <div class="form-group mb-8">
            <div class="alert alert-custom alert-danger" role="alert">
                <div class="alert-icon"><span
                        class="svg-icon svg-icon-default svg-icon-xl">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Tools/Compass.svg--><svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="24px" height="24px" viewBox="0 0 24 24"
                            version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24"/>
                                <circle fill="#000000" opacity="0.3" cx="12" cy="12" r="10"/>
                                <path d="M12.0355339,10.6213203 L14.863961,7.79289322 C15.2544853,7.40236893 15.8876503,7.40236893 16.2781746,7.79289322 C16.6686989,8.18341751 16.6686989,8.81658249 16.2781746,9.20710678 L13.4497475,12.0355339 L16.2781746,14.863961 C16.6686989,15.2544853 16.6686989,15.8876503 16.2781746,16.2781746 C15.8876503,16.6686989 15.2544853,16.6686989 14.863961,16.2781746 L12.0355339,13.4497475 L9.20710678,16.2781746 C8.81658249,16.6686989 8.18341751,16.6686989 7.79289322,16.2781746 C7.40236893,15.8876503 7.40236893,15.2544853 7.79289322,14.863961 L10.6213203,12.0355339 L7.79289322,9.20710678 C7.40236893,8.81658249 7.40236893,8.18341751 7.79289322,7.79289322 C8.18341751,7.40236893 8.81658249,7.40236893 9.20710678,7.79289322 L12.0355339,10.6213203 Z" fill="#000000"/>
                            </g>
                        </svg>
                        <!--end::Svg Icon--></span></div>
                <div class="alert-text">
                    @foreach ($errors->all() as $error)
                        {{ $error }} <br>
                    @endforeach
                </div>
            </div>
        </div>                    
    @endif
    
    <div class="form-group">
        <label name="nombre">Nombre Camion<span class="text-danger">*</span></label>
        <input name="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" value="{{ old('nombre', $camion->nombre) }}" placeholder="Camion" />
    </div>
    <div class="form-group mb-1">
        <label name="descripcion" for="exampleTextarea">Descripción del camión</label>
        <textarea name="descripcion"  class="form-control @error('descripcion') is-invalid @enderror" id="exampleTextarea"
            rows="3">{{ old('descripcion', $camion->descripcion) }}</textarea>
    </div>
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary btn-block">Guardar</button>
    <a href="{{ route('categoria.index') }}" class="btn btn-secondary btn-block">Cancelar</a>
</div>

resources/views/camion/index.blade.php
@extends('layouts.index')

@section('content')
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
        <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">
                        Camiones 
                    </h5>
                    <!--end::Page Title-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <a href="{{ route('camion.create') }}" class="btn btn-light-primary font-weight-bolder btn-sm">
                    Añadir Nuevo
                </a>
                <!--end::Actions-->
            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">
            @include('layouts.sessiones')
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <!--begin::Form-->
                <div class="card-body">
                    <!--begin: Datatable-->
                    <table class="table table-striped table-bordered" id="kt_datatable">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($camiones as $camion)
                                <tr>
                                    <td>{{ $camion->nombre }}</td>
                                    <td>{{ $camion->descripcion }}</td>
                                    <td>
                                        <a href="{{ route('camion.edit', $camion) }}" title="Editar" class="mr-5"><i class="flaticon2-pen text-primary"></i></a>
                                        <a href="{{ route('camion.edit', $camion) }}" title="Eliminar" class="mr-5"><i class="flaticon-delete text-primary"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <!--end: Datatable-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection